# Use the official Node.js image.
FROM node:18

# Create and change to the app directory.
WORKDIR /app

# Install app dependencies.
COPY package*.json ./
RUN npm install

# Copy the local code to the container image.
COPY . .

# Build the app.
RUN npm run build

# Expose the port the app runs on.
EXPOSE 3000

# Run the app.
CMD ["npx", "serve", "-s", "build"]
